plugins:
filters:
  comments: true
  allowlist:
    allow:
rules:
  preset-ja-technical-writing:
    no-doubled-joshi: false
    sentence-length:
      max: 1000
  preset-ja-spacing: true
  aws-service-name: true
  ja-hiragana-daimeishi: true
  ja-hiragana-fukushi: true
  ja-hiragana-hojodoushi: true
  ja-keishikimeishi: true
  ja-no-abusage: true
  no-mixed-zenkaku-and-hankaku-alphabet: true
  prh:
    rulePaths:
      - ./.prh.yml
