name: CI

on:
  push:
    branches: main
  pull_request:
    types:
      - opened
      - synchronize

env:
  LINT_TARGETS: ./articles/*.md ./books/*.md

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - uses: tsuyoshicho/action-textlint@ace6abb4fd6736f30f2319c7e21b7adf4e93dc46 # v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          textlint_flags: ${{ env.LINT_TARGETS }}

      - uses: DavidAnson/markdownlint-cli2-action@21c1be1b93ad9ed58fa840aacc3f279cde2a72ff # v24
        with:
          config: .markdownlint-cli2.jsonc
          globs: ${{ env.LINT_TARGETS }}

      - uses: streetsidesoftware/cspell-action@e0668cf020899e887ee8ad4d173c31738a79eae8 # v9
        with:
          config: ./cspell.yml
          files: ${{ env.LINT_TARGETS }}
